"""empty message

Revision ID: 7e77aee1acaf
Revises: fbc73eae937a
Create Date: 2016-06-13 21:43:06.405867

"""

# revision identifiers, used by Alembic.
revision = '7e77aee1acaf'
down_revision = 'fbc73eae937a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
